/**
 * Curated GeoGuesser locations — each entry has coordinates, display info, and a text clue.
 * `zoom` controls the OSM tile zoom for the location image (higher = more zoomed in).
 */
const LOCATIONS = [
  { lat: 48.8584, lng: 2.2945, name: 'Eiffel Tower', country: 'France', clue: 'An iron lattice tower built for a world fair in 1889.', zoom: 14 },
  { lat: 40.6892, lng: -74.0445, name: 'Statue of Liberty', country: 'USA', clue: 'A copper statue gifted by France, standing on an island in a harbor.', zoom: 14 },
  { lat: 27.1751, lng: 78.0421, name: 'Taj Mahal', country: 'India', clue: 'A white marble mausoleum built by a Mughal emperor for his wife.', zoom: 14 },
  { lat: -33.8568, lng: 151.2153, name: 'Sydney Opera House', country: 'Australia', clue: 'Sail-shaped shells on a harbor, an iconic performing arts center.', zoom: 14 },
  { lat: 41.8902, lng: 12.4922, name: 'Colosseum', country: 'Italy', clue: 'An ancient amphitheatre that once hosted gladiatorial contests.', zoom: 14 },
  { lat: 51.5014, lng: -0.1419, name: 'Big Ben', country: 'United Kingdom', clue: 'A famous clock tower beside a river, near the Houses of Parliament.', zoom: 14 },
  { lat: 35.6762, lng: 139.6503, name: 'Tokyo Tower', country: 'Japan', clue: 'A red-and-white communications tower inspired by a Parisian landmark.', zoom: 13 },
  { lat: -22.9519, lng: -43.2105, name: 'Christ the Redeemer', country: 'Brazil', clue: 'A giant statue atop a mountain overlooking a famous bay and city.', zoom: 13 },
  { lat: 29.9792, lng: 31.1342, name: 'Great Pyramid of Giza', country: 'Egypt', clue: 'The last surviving wonder of the ancient world, on a desert plateau.', zoom: 14 },
  { lat: 40.4319, lng: 116.5704, name: 'Great Wall of China', country: 'China', clue: 'A massive ancient fortification winding over mountains and hills.', zoom: 12 },
  { lat: 37.8199, lng: -122.4783, name: 'Golden Gate Bridge', country: 'USA', clue: 'An iconic red suspension bridge spanning the entrance to a bay.', zoom: 13 },
  { lat: 43.7230, lng: 10.3966, name: 'Leaning Tower of Pisa', country: 'Italy', clue: 'A white marble bell tower famous for its unintended tilt.', zoom: 15 },
  { lat: -13.1631, lng: -72.5450, name: 'Machu Picchu', country: 'Peru', clue: 'An ancient Inca citadel set high in the Andes mountains.', zoom: 14 },
  { lat: 47.5576, lng: 10.7498, name: 'Neuschwanstein Castle', country: 'Germany', clue: 'A fairy-tale castle perched on a rugged hill in Bavaria.', zoom: 14 },
  { lat: 55.7539, lng: 37.6208, name: 'Red Square', country: 'Russia', clue: 'A grand plaza next to colorful onion-domed cathedral and a famous wall.', zoom: 14 },
  { lat: 13.4125, lng: 103.8670, name: 'Angkor Wat', country: 'Cambodia', clue: 'The world\'s largest religious monument, surrounded by a moat.', zoom: 14 },
  { lat: 36.1005, lng: -112.1124, name: 'Grand Canyon', country: 'USA', clue: 'A steep-sided canyon carved by a river, over a mile deep.', zoom: 12 },
  { lat: -25.3444, lng: 131.0369, name: 'Uluru', country: 'Australia', clue: 'A massive sandstone monolith in the red center of a continent.', zoom: 13 },
  { lat: 64.1466, lng: -21.9426, name: 'Hallgrímskirkja', country: 'Iceland', clue: 'A towering concrete church shaped like basalt columns in a northern capital.', zoom: 14 },
  { lat: 1.2834, lng: 103.8607, name: 'Marina Bay Sands', country: 'Singapore', clue: 'Three towers topped by a sky-high infinity pool shaped like a surfboard.', zoom: 14 },
  { lat: 48.2082, lng: 16.3738, name: 'St. Stephen\'s Cathedral', country: 'Austria', clue: 'A Gothic cathedral with a colorful tiled roof in a city of music.', zoom: 14 },
  { lat: 41.0082, lng: 28.9784, name: 'Hagia Sophia', country: 'Turkey', clue: 'A domed masterpiece that served as cathedral, mosque, museum, and mosque again.', zoom: 14 },
  { lat: 34.1341, lng: -118.3215, name: 'Hollywood Sign', country: 'USA', clue: 'Giant white letters on a hillside in a city known for movies.', zoom: 14 },
  { lat: 50.0875, lng: 14.4213, name: 'Charles Bridge', country: 'Czech Republic', clue: 'A historic stone bridge lined with baroque statues over the Vltava River.', zoom: 14 },
  { lat: -33.8688, lng: 18.4241, name: 'Table Mountain', country: 'South Africa', clue: 'A flat-topped mountain overlooking a coastal city at the tip of a continent.', zoom: 13 },
  { lat: 25.1972, lng: 55.2744, name: 'Burj Khalifa', country: 'UAE', clue: 'The tallest building in the world, a supertall skyscraper in the desert.', zoom: 14 },
  { lat: 38.8977, lng: -77.0365, name: 'White House', country: 'USA', clue: 'A neoclassical mansion that serves as the executive residence of a president.', zoom: 15 },
  { lat: 59.3293, lng: 18.0686, name: 'Gamla Stan', country: 'Sweden', clue: 'A medieval old town on an island, with narrow cobblestone streets and colorful buildings.', zoom: 14 },
  { lat: 35.0116, lng: 135.7681, name: 'Kinkaku-ji', country: 'Japan', clue: 'A golden pavilion reflected in a mirror pond, a Zen Buddhist temple.', zoom: 15 },
  { lat: 52.5163, lng: 13.3777, name: 'Brandenburg Gate', country: 'Germany', clue: 'An 18th-century neoclassical monument that once divided a city in two.', zoom: 15 },
  { lat: 19.4326, lng: -99.1332, name: 'Zócalo', country: 'Mexico', clue: 'One of the largest public squares in the world, at the heart of an ancient lake city.', zoom: 14 },
  { lat: -34.6037, lng: -58.3816, name: 'Obelisco', country: 'Argentina', clue: 'A tall obelisk in the middle of the widest avenue in the world.', zoom: 14 },
  { lat: 37.9715, lng: 23.7267, name: 'Acropolis', country: 'Greece', clue: 'An ancient citadel on a rocky hill with temples dedicated to a goddess.', zoom: 14 },
  { lat: 30.3285, lng: 35.4444, name: 'Petra', country: 'Jordan', clue: 'A rose-red city half as old as time, carved into sandstone cliffs.', zoom: 13 },
  { lat: 12.3714, lng: -1.5197, name: 'Ouagadougou', country: 'Burkina Faso', clue: 'The capital city of a West African landlocked nation, known for its film festival.', zoom: 12 },
  { lat: -4.0435, lng: 39.6682, name: 'Fort Jesus', country: 'Kenya', clue: 'A Portuguese fort on the coast of East Africa, guarding an old port city.', zoom: 14 },
  { lat: 3.1390, lng: 101.6869, name: 'Petronas Towers', country: 'Malaysia', clue: 'Twin skyscrapers connected by a sky bridge, once the tallest buildings in the world.', zoom: 14 },
  { lat: 46.2044, lng: 6.1432, name: 'Jet d\'Eau', country: 'Switzerland', clue: 'A tall fountain shooting water 140m into the air on a lakefront.', zoom: 14 },
  { lat: 53.3498, lng: -6.2603, name: 'Ha\'penny Bridge', country: 'Ireland', clue: 'A cast-iron pedestrian bridge over a river in a city famous for its pubs.', zoom: 15 },
  { lat: 21.4225, lng: 39.8262, name: 'Kaaba', country: 'Saudi Arabia', clue: 'The holiest site in Islam, a cube-shaped structure in a grand mosque.', zoom: 14 },
  { lat: 39.9042, lng: 116.3974, name: 'Forbidden City', country: 'China', clue: 'A vast palace complex that was home to emperors for 500 years.', zoom: 14 },
  { lat: -15.7975, lng: -47.8919, name: 'Cathedral of Brasília', country: 'Brazil', clue: 'A hyperboloid structure of curved concrete columns in a planned capital.', zoom: 14 },
  { lat: 60.1699, lng: 24.9384, name: 'Helsinki Cathedral', country: 'Finland', clue: 'A white neoclassical cathedral atop a grand staircase in a Nordic capital.', zoom: 14 },
  { lat: -41.2865, lng: 174.7762, name: 'Wellington Beehive', country: 'New Zealand', clue: 'A distinctive round executive wing of a parliament in a windy capital.', zoom: 14 },
  { lat: 6.5244, lng: 3.3792, name: 'Lekki Conservation Centre', country: 'Nigeria', clue: 'A nature reserve with the longest canopy walkway in Africa, in a megacity.', zoom: 13 },
  { lat: 23.8103, lng: 90.4125, name: 'Ahsan Manzil', country: 'Bangladesh', clue: 'A pink palace on a riverbank, former seat of the Nawabs of Dhaka.', zoom: 14 },
  { lat: 14.5995, lng: 120.9842, name: 'Rizal Park', country: 'Philippines', clue: 'A large urban park named after a national hero, in the oldest district of a capital.', zoom: 14 },
  { lat: 4.7110, lng: -74.0721, name: 'Monserrate', country: 'Colombia', clue: 'A hilltop basilica overlooking a sprawling city in the Andes.', zoom: 13 },
  { lat: 33.8938, lng: 35.5018, name: 'Pigeon Rocks', country: 'Lebanon', clue: 'Natural sea arches off the coast of a Mediterranean capital.', zoom: 14 },
  { lat: 28.6139, lng: 77.2090, name: 'India Gate', country: 'India', clue: 'A war memorial arch on a grand ceremonial avenue in a capital city.', zoom: 14 },
];

export default LOCATIONS;
