/**
 * Generates runnable JavaScript bot code from no-code builder rules.
 * Output uses StoatBotClient and EmbedBuilder from stoat-bot-sdk.
 */

const ESCAPE_JS_STRING = (s) => {
  if (s == null) return '""';
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
};

function replaceUserPlaceholders(str) {
  if (str == null || !str.length) return '""';
  return ESCAPE_JS_STRING(str) + ".replace(/\\$user/g, \`<@\${userId}>\`).replace(/\\{username\\}/g, username || 'User')";
}

function embedToCode(embed, options = {}) {
  const { wrapInReplaceUser = false } = options;
  const lines = [];
  const title = embed?.title ?? '';
  const description = embed?.description ?? '';
  const color = embed?.color ?? '#5865f2';
  lines.push('  const embed = new EmbedBuilder()');
  if (title) {
    if (wrapInReplaceUser && (title.includes('$user') || title.includes('{username}'))) {
      lines.push(`    .setTitle(${replaceUserPlaceholders(title)})`);
    } else {
      lines.push(`    .setTitle(${ESCAPE_JS_STRING(title)})`);
    }
  }
  if (description) {
    if (wrapInReplaceUser && (description.includes('$user') || description.includes('{username}'))) {
      lines.push(`    .setDescription(${replaceUserPlaceholders(description)})`);
    } else {
      lines.push(`    .setDescription(${ESCAPE_JS_STRING(description)})`);
    }
  }
  if (color && /^#?[0-9a-fA-F]{6}$/.test(color.replace('#', ''))) {
    lines.push(`    .setColor(${ESCAPE_JS_STRING(color)})`);
  }
  const fields = embed?.fields || [];
  for (const f of fields) {
    if (f.name != null || f.value != null) {
      lines.push(`    .addField(${ESCAPE_JS_STRING(f.name || '')}, ${ESCAPE_JS_STRING(f.value || '')}, ${!!f.inline})`);
    }
  }
  if (embed?.footer) {
    lines.push(`    .setFooter(${ESCAPE_JS_STRING(embed.footer)})`);
  }
  if (embed?.imageUrl) {
    lines.push(`    .setImage(${ESCAPE_JS_STRING(embed.imageUrl)})`);
  }
  lines.push('    .toJSON();');
  return lines.join('\n');
}

export function generateBotCode(rules = [], options = {}) {
  const prefix = options.prefix ?? '!';
  const baseUrl = options.baseUrl ?? 'http://localhost:14702';
  const intentsSet = new Set(['GUILDS', 'GUILD_MESSAGES', 'MESSAGE_CONTENT']);
  const hasCommand = rules.some((r) => r.trigger?.type === 'command');
  const hasEmbed = rules.some((r) => r.trigger?.responseType === 'embed' && r.trigger?.responseEmbed);
  for (const rule of rules) {
    const t = rule.trigger?.type;
    if (t === 'member_join') intentsSet.add('GUILD_MEMBERS');
    if (t === 'keyword') intentsSet.add('MESSAGE_CONTENT');
  }
  const intents = Array.from(intentsSet);

  const lines = [];
  lines.push('/**');
  lines.push(' * Generated by Stoat Bot Builder');
  lines.push(' * Run: BOT_TOKEN=your_token node bot.js');
  lines.push(' */');
  lines.push('');
  const importParts = ["StoatBotClient", "GatewayIntents", "GatewayEvents"];
  if (hasEmbed) importParts.push("EmbedBuilder");
  lines.push(`import { ${importParts.join(", ")} } from 'stoat-bot-sdk';`);
  lines.push('');
  lines.push('const token = process.env.BOT_TOKEN;');
  lines.push("if (!token) { console.error('Set BOT_TOKEN'); process.exit(1); }");
  lines.push('');
  lines.push('const bot = new StoatBotClient({');
  lines.push('  token,');
  lines.push(`  baseUrl: process.env.BOT_API_BASE || ${ESCAPE_JS_STRING(baseUrl)},`);
  lines.push(`  intents: GatewayIntents.${intents[0]} | GatewayIntents.${intents[1]} | GatewayIntents.${intents[2]}${intents[3] ? ` | GatewayIntents.${intents[3]}` : ''},`);
  lines.push(`  prefix: ${ESCAPE_JS_STRING(prefix)},`);
  lines.push('});');
  lines.push('');
  lines.push("bot.on('open', () => console.log('Bot connected'));");
  lines.push("bot.on(GatewayEvents.READY, (d) => console.log('Ready as', d?.users?.[0]?.username || 'bot'));");
  lines.push("bot.on('error', (err) => console.error(err));");
  if (hasCommand) {
    lines.push('bot.startCommandRouter();');
    lines.push('');
  }

  for (let i = 0; i < rules.length; i++) {
    const rule = rules[i];
    const trigger = rule.trigger || {};
    const actions = Array.isArray(rule.actions) ? rule.actions : [];
    const useEmbed = trigger.responseType === 'embed' && trigger.responseEmbed;

    if (trigger.type === 'member_join') {
      const channelId = trigger.channelId || 'WELCOME_CHANNEL_ID';
      lines.push(`// Rule ${i + 1}: When someone joins the server`);
      lines.push('bot.on(GatewayEvents.SERVER_MEMBER_JOIN, async (data) => {');
      lines.push('  const userId = data?.member?.user?._id ?? data?.member?.user;');
      lines.push('  const username = data?.member?.user?.display_name || data?.member?.user?.username;');
      lines.push('  if (!userId) return;');
      lines.push(`  const channelId = process.env.WELCOME_CHANNEL_ID || ${ESCAPE_JS_STRING(channelId)};`);
      lines.push('  try {');
      if (useEmbed) {
        lines.push(embedToCode(trigger.responseEmbed, { wrapInReplaceUser: true }));
        lines.push('    await bot.sendMessage(channelId, "", { embeds: [embed], mentions: [userId] });');
      } else {
        const template = trigger.messageTemplate || 'Welcome $user!';
        lines.push(`    const content = ${ESCAPE_JS_STRING(template)}.replace(/\\$user/g, \`<@\${userId}>\`).replace(/\\{username\\}/g, username || 'User');`);
        lines.push('    await bot.sendMessage(channelId, content, { mentions: [userId] });');
      }
      lines.push('  } catch (e) { console.error(e); }');
      lines.push('});');
      lines.push('');
    }

    if (trigger.type === 'command') {
      const cmdName = trigger.commandName || 'ping';
      lines.push(`// Rule ${i + 1}: Command !${cmdName}`);
      lines.push(`bot.command(${ESCAPE_JS_STRING(cmdName)}, async (ctx) => {`);
      if (useEmbed) {
        lines.push(embedToCode(trigger.responseEmbed));
        lines.push('  await ctx.reply(ctx.message, "", { embeds: [embed] });');
      } else {
        const response = actions[0]?.content ?? trigger.response ?? 'Pong!';
        lines.push(`  await ctx.reply(${ESCAPE_JS_STRING(response)});`);
      }
      lines.push('});');
      lines.push('');
    }

    if (trigger.type === 'keyword') {
      const keyword = trigger.keyword || 'hello';
      const caseSensitive = trigger.caseSensitive ?? false;
      lines.push(`// Rule ${i + 1}: When message contains "${keyword}"`);
      lines.push('bot.on(GatewayEvents.MESSAGE_CREATE, async (msg) => {');
      lines.push('  const content = msg?.content ?? msg?.d?.content ?? "";');
      if (caseSensitive) {
        lines.push(`  if (!content.includes(${ESCAPE_JS_STRING(keyword)})) return;`);
      } else {
        lines.push(`  if (!content.toLowerCase().includes(${ESCAPE_JS_STRING(keyword.toLowerCase())})) return;`);
      }
      lines.push('  if (msg?.author?.bot) return;');
      lines.push('  const channelId = msg?.channel ?? msg?.d?.channel;');
      lines.push('  if (!channelId) return;');
      lines.push('  try {');
      if (useEmbed) {
        lines.push(embedToCode(trigger.responseEmbed));
        lines.push('    await bot.sendMessage(channelId, "", { embeds: [embed] });');
      } else {
        const response = actions[0]?.content ?? trigger.response ?? 'Hi there!';
        lines.push(`    await bot.sendMessage(channelId, ${ESCAPE_JS_STRING(response)});`);
      }
      lines.push('  } catch (e) { console.error(e); }');
      lines.push('});');
      lines.push('');
    }
  }

  lines.push('await bot.connect();');
  lines.push('');
  return lines.join('\n');
}
