const EMOJI_DATA = [
  { cat: 'Smileys', emojis: [
    { e: '😀', n: 'grinning' }, { e: '😃', n: 'smiley' }, { e: '😄', n: 'smile' },
    { e: '😁', n: 'grin' }, { e: '😆', n: 'laughing' }, { e: '😅', n: 'sweat_smile' },
    { e: '🤣', n: 'rofl' }, { e: '😂', n: 'joy' }, { e: '🙂', n: 'slightly_smiling' },
    { e: '🙃', n: 'upside_down' }, { e: '😉', n: 'wink' }, { e: '😊', n: 'blush' },
    { e: '😇', n: 'innocent' }, { e: '🥰', n: 'smiling_hearts' }, { e: '😍', n: 'heart_eyes' },
    { e: '🤩', n: 'star_struck' }, { e: '😘', n: 'kissing_heart' }, { e: '😗', n: 'kissing' },
    { e: '😚', n: 'kissing_closed_eyes' }, { e: '😙', n: 'kissing_smiling_eyes' },
    { e: '🥲', n: 'smiling_tear' }, { e: '😋', n: 'yum' }, { e: '😛', n: 'stuck_out_tongue' },
    { e: '😜', n: 'stuck_out_tongue_winking' }, { e: '🤪', n: 'zany' },
    { e: '😝', n: 'stuck_out_tongue_closed_eyes' }, { e: '🤑', n: 'money_mouth' },
    { e: '🤗', n: 'hugging' }, { e: '🤭', n: 'hand_over_mouth' }, { e: '🤫', n: 'shushing' },
    { e: '🤔', n: 'thinking' }, { e: '🫡', n: 'saluting' }, { e: '🤐', n: 'zipper_mouth' },
    { e: '🤨', n: 'raised_eyebrow' }, { e: '😐', n: 'neutral' }, { e: '😑', n: 'expressionless' },
    { e: '😶', n: 'no_mouth' }, { e: '🫥', n: 'dotted_line' }, { e: '😏', n: 'smirk' },
    { e: '😒', n: 'unamused' }, { e: '🙄', n: 'rolling_eyes' }, { e: '😬', n: 'grimacing' },
    { e: '🤥', n: 'lying' }, { e: '😌', n: 'relieved' }, { e: '😔', n: 'pensive' },
    { e: '😪', n: 'sleepy' }, { e: '🤤', n: 'drooling' }, { e: '😴', n: 'sleeping' },
    { e: '😷', n: 'mask' }, { e: '🤒', n: 'thermometer_face' }, { e: '🤕', n: 'head_bandage' },
    { e: '🤢', n: 'nauseated' }, { e: '🤮', n: 'vomiting' }, { e: '🤧', n: 'sneezing' },
    { e: '🥵', n: 'hot' }, { e: '🥶', n: 'cold' }, { e: '🥴', n: 'woozy' },
    { e: '😵', n: 'dizzy_face' }, { e: '🤯', n: 'exploding_head' }, { e: '🤠', n: 'cowboy' },
    { e: '🥳', n: 'partying' }, { e: '🥸', n: 'disguised' }, { e: '😎', n: 'sunglasses' },
    { e: '🤓', n: 'nerd' }, { e: '🧐', n: 'monocle' }, { e: '😕', n: 'confused' },
    { e: '🫤', n: 'diagonal_mouth' }, { e: '😟', n: 'worried' }, { e: '🙁', n: 'slightly_frowning' },
    { e: '😮', n: 'open_mouth' }, { e: '😯', n: 'hushed' }, { e: '😲', n: 'astonished' },
    { e: '😳', n: 'flushed' }, { e: '🥺', n: 'pleading' }, { e: '🥹', n: 'holding_back_tears' },
    { e: '😦', n: 'frowning' }, { e: '😧', n: 'anguished' }, { e: '😨', n: 'fearful' },
    { e: '😰', n: 'anxious_sweat' }, { e: '😥', n: 'sad_relieved' }, { e: '😢', n: 'cry' },
    { e: '😭', n: 'sob' }, { e: '😱', n: 'scream' }, { e: '😖', n: 'confounded' },
    { e: '😣', n: 'persevere' }, { e: '😞', n: 'disappointed' }, { e: '😓', n: 'downcast_sweat' },
    { e: '😩', n: 'weary' }, { e: '😫', n: 'tired' }, { e: '🥱', n: 'yawning' },
    { e: '😤', n: 'triumph' }, { e: '😡', n: 'rage' }, { e: '😠', n: 'angry' },
    { e: '🤬', n: 'cursing' }, { e: '😈', n: 'smiling_imp' }, { e: '👿', n: 'imp' },
    { e: '💀', n: 'skull' }, { e: '☠️', n: 'skull_crossbones' }, { e: '💩', n: 'poop' },
    { e: '🤡', n: 'clown' }, { e: '👹', n: 'ogre' }, { e: '👺', n: 'goblin' },
    { e: '👻', n: 'ghost' }, { e: '👽', n: 'alien' }, { e: '👾', n: 'space_invader' },
    { e: '🤖', n: 'robot' },
  ]},
  { cat: 'Gestures', emojis: [
    { e: '👋', n: 'wave' }, { e: '🤚', n: 'raised_back_hand' }, { e: '🖐️', n: 'splayed_hand' },
    { e: '✋', n: 'raised_hand' }, { e: '🖖', n: 'vulcan' }, { e: '🫱', n: 'rightwards_hand' },
    { e: '🫲', n: 'leftwards_hand' }, { e: '🫳', n: 'palm_down' }, { e: '🫴', n: 'palm_up' },
    { e: '👌', n: 'ok_hand' }, { e: '🤌', n: 'pinched_fingers' }, { e: '🤏', n: 'pinching' },
    { e: '✌️', n: 'v' }, { e: '🤞', n: 'crossed_fingers' }, { e: '🫰', n: 'hand_with_index_crossed' },
    { e: '🤟', n: 'love_you' }, { e: '🤘', n: 'metal' }, { e: '🤙', n: 'call_me' },
    { e: '👈', n: 'point_left' }, { e: '👉', n: 'point_right' }, { e: '👆', n: 'point_up' },
    { e: '🖕', n: 'middle_finger' }, { e: '👇', n: 'point_down' }, { e: '☝️', n: 'point_up_2' },
    { e: '🫵', n: 'index_pointing_at_viewer' }, { e: '👍', n: 'thumbsup' },
    { e: '👎', n: 'thumbsdown' }, { e: '✊', n: 'fist' }, { e: '👊', n: 'punch' },
    { e: '🤛', n: 'left_fist' }, { e: '🤜', n: 'right_fist' }, { e: '👏', n: 'clap' },
    { e: '🙌', n: 'raised_hands' }, { e: '🫶', n: 'heart_hands' }, { e: '👐', n: 'open_hands' },
    { e: '🤲', n: 'palms_up' }, { e: '🤝', n: 'handshake' }, { e: '🙏', n: 'pray' },
    { e: '✍️', n: 'writing' }, { e: '💪', n: 'muscle' }, { e: '🦾', n: 'mechanical_arm' },
    { e: '🦿', n: 'mechanical_leg' }, { e: '🦵', n: 'leg' }, { e: '🦶', n: 'foot' },
    { e: '👂', n: 'ear' }, { e: '👃', n: 'nose' }, { e: '🧠', n: 'brain' },
    { e: '👀', n: 'eyes' }, { e: '👁️', n: 'eye' }, { e: '👅', n: 'tongue' }, { e: '👄', n: 'lips' },
  ]},
  { cat: 'Hearts', emojis: [
    { e: '❤️', n: 'red_heart' }, { e: '🧡', n: 'orange_heart' }, { e: '💛', n: 'yellow_heart' },
    { e: '💚', n: 'green_heart' }, { e: '💙', n: 'blue_heart' }, { e: '💜', n: 'purple_heart' },
    { e: '🖤', n: 'black_heart' }, { e: '🤍', n: 'white_heart' }, { e: '🤎', n: 'brown_heart' },
    { e: '💔', n: 'broken_heart' }, { e: '❤️‍🔥', n: 'heart_on_fire' }, { e: '❤️‍🩹', n: 'mending_heart' },
    { e: '💕', n: 'two_hearts' }, { e: '💞', n: 'revolving_hearts' }, { e: '💓', n: 'heartbeat' },
    { e: '💗', n: 'heartpulse' }, { e: '💖', n: 'sparkling_heart' }, { e: '💘', n: 'cupid' },
    { e: '💝', n: 'gift_heart' }, { e: '💟', n: 'heart_decoration' },
  ]},
  { cat: 'Nature', emojis: [
    { e: '🐶', n: 'dog' }, { e: '🐱', n: 'cat' }, { e: '🐭', n: 'mouse' },
    { e: '🐹', n: 'hamster' }, { e: '🐰', n: 'rabbit' }, { e: '🦊', n: 'fox' },
    { e: '🐻', n: 'bear' }, { e: '🐼', n: 'panda' }, { e: '🐨', n: 'koala' },
    { e: '🐯', n: 'tiger' }, { e: '🦁', n: 'lion' }, { e: '🐮', n: 'cow' },
    { e: '🐷', n: 'pig' }, { e: '🐸', n: 'frog' }, { e: '🐵', n: 'monkey' },
    { e: '🙈', n: 'see_no_evil' }, { e: '🙉', n: 'hear_no_evil' }, { e: '🙊', n: 'speak_no_evil' },
    { e: '🐔', n: 'chicken' }, { e: '🐧', n: 'penguin' }, { e: '🐦', n: 'bird' },
    { e: '🐤', n: 'baby_chick' }, { e: '🦆', n: 'duck' }, { e: '🦅', n: 'eagle' },
    { e: '🦉', n: 'owl' }, { e: '🐺', n: 'wolf' }, { e: '🐗', n: 'boar' },
    { e: '🐴', n: 'horse' }, { e: '🦄', n: 'unicorn' }, { e: '🐝', n: 'bee' },
    { e: '🪱', n: 'worm' }, { e: '🐛', n: 'bug' }, { e: '🦋', n: 'butterfly' },
    { e: '🐌', n: 'snail' }, { e: '🐞', n: 'ladybug' }, { e: '🐜', n: 'ant' },
    { e: '🪲', n: 'beetle' }, { e: '🐢', n: 'turtle' }, { e: '🐍', n: 'snake' },
    { e: '🦎', n: 'lizard' }, { e: '🐙', n: 'octopus' }, { e: '🦑', n: 'squid' },
    { e: '🦐', n: 'shrimp' }, { e: '🦀', n: 'crab' }, { e: '🐠', n: 'tropical_fish' },
    { e: '🐟', n: 'fish' }, { e: '🐬', n: 'dolphin' }, { e: '🐳', n: 'whale' },
    { e: '🦈', n: 'shark' }, { e: '🐊', n: 'crocodile' }, { e: '🐘', n: 'elephant' },
    { e: '🦬', n: 'bison' }, { e: '🦏', n: 'rhino' }, { e: '🦛', n: 'hippo' },
    { e: '🌵', n: 'cactus' }, { e: '🎄', n: 'christmas_tree' }, { e: '🌲', n: 'evergreen_tree' },
    { e: '🌳', n: 'deciduous_tree' }, { e: '🌴', n: 'palm_tree' }, { e: '🌱', n: 'seedling' },
    { e: '🌿', n: 'herb' }, { e: '🍀', n: 'four_leaf_clover' }, { e: '🍁', n: 'maple_leaf' },
    { e: '🍂', n: 'fallen_leaf' }, { e: '🍃', n: 'leaves' }, { e: '🌺', n: 'hibiscus' },
    { e: '🌻', n: 'sunflower' }, { e: '🌹', n: 'rose' }, { e: '🌷', n: 'tulip' },
    { e: '🌸', n: 'cherry_blossom' },
  ]},
  { cat: 'Food', emojis: [
    { e: '🍎', n: 'apple' }, { e: '🍐', n: 'pear' }, { e: '🍊', n: 'orange' },
    { e: '🍋', n: 'lemon' }, { e: '🍌', n: 'banana' }, { e: '🍉', n: 'watermelon' },
    { e: '🍇', n: 'grapes' }, { e: '🍓', n: 'strawberry' }, { e: '🫐', n: 'blueberries' },
    { e: '🍈', n: 'melon' }, { e: '🍒', n: 'cherries' }, { e: '🍑', n: 'peach' },
    { e: '🥭', n: 'mango' }, { e: '🍍', n: 'pineapple' }, { e: '🥥', n: 'coconut' },
    { e: '🥝', n: 'kiwi' }, { e: '🍅', n: 'tomato' }, { e: '🥑', n: 'avocado' },
    { e: '🍕', n: 'pizza' }, { e: '🍔', n: 'hamburger' }, { e: '🍟', n: 'fries' },
    { e: '🌭', n: 'hotdog' }, { e: '🥪', n: 'sandwich' }, { e: '🌮', n: 'taco' },
    { e: '🌯', n: 'burrito' }, { e: '🍿', n: 'popcorn' }, { e: '🧀', n: 'cheese' },
    { e: '🥚', n: 'egg' }, { e: '🍳', n: 'cooking' }, { e: '🥓', n: 'bacon' },
    { e: '🥩', n: 'steak' }, { e: '🍗', n: 'poultry_leg' }, { e: '🍖', n: 'meat_on_bone' },
    { e: '🍰', n: 'cake' }, { e: '🎂', n: 'birthday' }, { e: '🧁', n: 'cupcake' },
    { e: '🍩', n: 'doughnut' }, { e: '🍪', n: 'cookie' }, { e: '🍫', n: 'chocolate' },
    { e: '🍬', n: 'candy' }, { e: '🍭', n: 'lollipop' }, { e: '🍮', n: 'custard' },
    { e: '🍯', n: 'honey' }, { e: '☕', n: 'coffee' }, { e: '🍵', n: 'tea' },
    { e: '🧃', n: 'juice_box' }, { e: '🥤', n: 'cup_straw' }, { e: '🍺', n: 'beer' },
    { e: '🍻', n: 'beers' }, { e: '🥂', n: 'champagne' }, { e: '🍷', n: 'wine' },
    { e: '🍸', n: 'cocktail' }, { e: '🍹', n: 'tropical_drink' },
  ]},
  { cat: 'Activities', emojis: [
    { e: '⚽', n: 'soccer' }, { e: '🏀', n: 'basketball' }, { e: '🏈', n: 'football' },
    { e: '⚾', n: 'baseball' }, { e: '🥎', n: 'softball' }, { e: '🎾', n: 'tennis' },
    { e: '🏐', n: 'volleyball' }, { e: '🏉', n: 'rugby' }, { e: '🎱', n: 'pool_8ball' },
    { e: '🏓', n: 'ping_pong' }, { e: '🏸', n: 'badminton' }, { e: '🥊', n: 'boxing' },
    { e: '🥋', n: 'martial_arts' }, { e: '⛳', n: 'golf' }, { e: '⛸️', n: 'ice_skate' },
    { e: '🎿', n: 'ski' }, { e: '🛷', n: 'sled' }, { e: '🎯', n: 'dart' },
    { e: '🎮', n: 'video_game' }, { e: '🕹️', n: 'joystick' }, { e: '🎲', n: 'game_die' },
    { e: '🧩', n: 'puzzle' }, { e: '🎪', n: 'circus' }, { e: '🎭', n: 'performing_arts' },
    { e: '🎨', n: 'art' }, { e: '🎬', n: 'clapper' }, { e: '🎤', n: 'microphone' },
    { e: '🎧', n: 'headphones' }, { e: '🎵', n: 'musical_note' }, { e: '🎶', n: 'notes' },
    { e: '🎸', n: 'guitar' }, { e: '🎹', n: 'musical_keyboard' }, { e: '🥁', n: 'drum' },
    { e: '🎺', n: 'trumpet' }, { e: '🎻', n: 'violin' }, { e: '🏆', n: 'trophy' },
    { e: '🥇', n: 'first_place' }, { e: '🥈', n: 'second_place' }, { e: '🥉', n: 'third_place' },
    { e: '🏅', n: 'medal' }, { e: '🎖️', n: 'military_medal' }, { e: '🎗️', n: 'ribbon' },
    { e: '🎁', n: 'gift' }, { e: '🎀', n: 'ribbon_bow' }, { e: '🎉', n: 'tada' },
    { e: '🎊', n: 'confetti' },
  ]},
  { cat: 'Objects', emojis: [
    { e: '💻', n: 'laptop' }, { e: '🖥️', n: 'desktop' }, { e: '⌨️', n: 'keyboard' },
    { e: '🖱️', n: 'mouse_computer' }, { e: '📱', n: 'phone' }, { e: '📞', n: 'telephone' },
    { e: '📷', n: 'camera' }, { e: '📹', n: 'video_camera' }, { e: '📺', n: 'tv' },
    { e: '🔌', n: 'plug' }, { e: '💡', n: 'bulb' }, { e: '🔦', n: 'flashlight' },
    { e: '📦', n: 'package' }, { e: '📧', n: 'email' }, { e: '📝', n: 'memo' },
    { e: '📚', n: 'books' }, { e: '📖', n: 'book' }, { e: '🔗', n: 'link' },
    { e: '📎', n: 'paperclip' }, { e: '✂️', n: 'scissors' }, { e: '📌', n: 'pushpin' },
    { e: '📍', n: 'round_pushpin' }, { e: '🔒', n: 'lock' }, { e: '🔓', n: 'unlock' },
    { e: '🔑', n: 'key' }, { e: '🗝️', n: 'old_key' }, { e: '🔨', n: 'hammer' },
    { e: '🪓', n: 'axe' }, { e: '⛏️', n: 'pick' }, { e: '🔧', n: 'wrench' },
    { e: '🔩', n: 'nut_bolt' }, { e: '⚙️', n: 'gear' }, { e: '🧲', n: 'magnet' },
    { e: '💣', n: 'bomb' }, { e: '🧨', n: 'firecracker' }, { e: '🪄', n: 'magic_wand' },
    { e: '🗡️', n: 'dagger' }, { e: '⚔️', n: 'crossed_swords' }, { e: '🛡️', n: 'shield' },
    { e: '🏹', n: 'bow_arrow' }, { e: '💎', n: 'gem' }, { e: '💰', n: 'money_bag' },
    { e: '💵', n: 'dollar' }, { e: '💳', n: 'credit_card' },
  ]},
  { cat: 'Symbols', emojis: [
    { e: '✅', n: 'white_check_mark' }, { e: '❌', n: 'x' }, { e: '❓', n: 'question' },
    { e: '❗', n: 'exclamation' }, { e: '‼️', n: 'bangbang' }, { e: '⁉️', n: 'interrobang' },
    { e: '💯', n: 'hundred' }, { e: '🔥', n: 'fire' }, { e: '✨', n: 'sparkles' },
    { e: '⭐', n: 'star' }, { e: '🌟', n: 'star2' }, { e: '💫', n: 'dizzy' },
    { e: '💥', n: 'boom' }, { e: '💢', n: 'anger' }, { e: '💤', n: 'zzz' },
    { e: '💬', n: 'speech_balloon' }, { e: '💭', n: 'thought_balloon' },
    { e: '🗯️', n: 'anger_right' }, { e: '🔔', n: 'bell' }, { e: '🔕', n: 'no_bell' },
    { e: '🎵', n: 'notes2' }, { e: '⚠️', n: 'warning' }, { e: '🚫', n: 'no_entry' },
    { e: '⛔', n: 'stop' }, { e: '🔞', n: 'underage' }, { e: '♻️', n: 'recycle' },
    { e: '✔️', n: 'check_mark' }, { e: '➡️', n: 'arrow_right' }, { e: '⬅️', n: 'arrow_left' },
    { e: '⬆️', n: 'arrow_up' }, { e: '⬇️', n: 'arrow_down' }, { e: '↩️', n: 'leftwards_arrow' },
    { e: '↪️', n: 'arrow_right_hook' }, { e: '🔃', n: 'arrows_clockwise' },
    { e: '🔄', n: 'arrows_counterclockwise' }, { e: '➕', n: 'plus' }, { e: '➖', n: 'minus' },
    { e: '➗', n: 'divide' }, { e: '✖️', n: 'multiply' }, { e: '♾️', n: 'infinity' },
    { e: '💲', n: 'dollar_sign' }, { e: '©️', n: 'copyright' }, { e: '®️', n: 'registered' },
    { e: '™️', n: 'tm' },
  ]},
  { cat: 'Flags', emojis: [
    { e: '🏁', n: 'checkered_flag' }, { e: '🚩', n: 'triangular_flag' },
    { e: '🏳️', n: 'white_flag' }, { e: '🏴', n: 'black_flag' },
    { e: '🏳️‍🌈', n: 'rainbow_flag' }, { e: '🏴‍☠️', n: 'pirate_flag' },
    { e: '🇺🇸', n: 'us' }, { e: '🇬🇧', n: 'gb' }, { e: '🇫🇷', n: 'fr' },
    { e: '🇩🇪', n: 'de' }, { e: '🇯🇵', n: 'jp' }, { e: '🇰🇷', n: 'kr' },
    { e: '🇨🇳', n: 'cn' }, { e: '🇧🇷', n: 'br' }, { e: '🇮🇳', n: 'in' },
    { e: '🇷🇺', n: 'ru' }, { e: '🇨🇦', n: 'ca' }, { e: '🇦🇺', n: 'au' },
    { e: '🇲🇽', n: 'mx' }, { e: '🇪🇸', n: 'es' }, { e: '🇮🇹', n: 'it' },
  ]},
];

export const ALL_EMOJIS = EMOJI_DATA.flatMap(c => c.emojis.map(e => ({ ...e, cat: c.cat })));

export function searchEmojis(query, limit = 25) {
  const q = query.toLowerCase();
  return ALL_EMOJIS.filter(e => e.n.includes(q)).slice(0, limit);
}

export default EMOJI_DATA;
